appnyajadi_1/urls.py
from django.conf.urls import url
from .views import index, add_forum, dashboard, delete_forum, add_comment
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_forum/(?P<id>.*)/$', add_forum, name='add_forum'),
	url(r'^dashboard', dashboard, name='dashboard'),
	url(r'^add_comment', add_comment, name = 'add_comment'),

	#url(r'^clear/(?P<object_id>[0-9]+)', view=clear, name='clear'),
	url(r'^delete_forum/(?P<id_status>\d+)/$', delete_forum, name = 'delete_forum'),

	# custom auth
	#url(r'^custom_auth/login/$', auth_login, name='auth_login'),
	#url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]
       
    

tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import appnyajadi_1.urls as appnyajadi_1

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^appnyajadi-1/', include(appnyajadi_1,namespace='appnyajadi-1')),
    #url(r'^forumku/', include(forumku,namespace='forumku')),  #url lila awal
]

appnyajadi_1/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Company(models.Model):
    company_name = models.CharField(max_length=50, default='DEFAULT VALUE')
    specialty = models.CharField(max_length=250, default='DEFAULT VALUE')
    yearFounded = models.CharField(max_length=5, default='DEFAULT VALUE')
    description = models.CharField(max_length=300, default='DEFAULT VALUE')
    website = models.CharField(max_length=300, default='DEFAULT VALUE')
    company_type = models.CharField(max_length=300, default='DEFAULT VALUE')
    url_foto = models.CharField(max_length=300, default='DEFAULT VALUE')

class Forum(models.Model):
    pengguna = models.ForeignKey(Company, default=1)
    isi = models.CharField('isi', max_length=400, default='DEFAULT VALUE')

class Comment(models.Model):
    forum = models.ForeignKey(Forum, default=1)
    nama = models.CharField('Nama', max_length=30, default='DEFAULT VALUE')
    description = models.TextField()


        

appnyajadi_1/forms.py
from django import forms

class Lowongan_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    nama_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Masukan judul...'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Masukan komentar...'
    }
    nama = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=nama_attrs))
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))


class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    title_attrs = {
        'class': 'form-control',
        'placeholder':'This post is about...'
    }

    message_attrs = {
        'class': 'form-control',
        'placeholder':'Your post is...'
    }

    title = forms.CharField(label='Judul Forum', required=True, max_length=30, widget=forms.TextInput(attrs=title_attrs))
    message = forms.CharField(widget=forms.Textarea(attrs=message_attrs), required=True)

class Comment_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }

    description_attrs ={
        'type': 'text',
        'cols': 60,
        'rows': 10,
        'class': 'comment-form-textarea',
        'placeholder':' Write your comment here. . '
    }
    comment = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

appnyajadi_1/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect    
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import Message_Form, Comment_Form, Lowongan_Form
from .models import Forum, Company, Comment

# Create your views here.
response={}
def index(request):    
    response['author'] = "Rama Widragama Putra dan Anas" #TODO Implement yourname
    response['lowongan_form'] = Lowongan_Form
    page = request.GET.get('page', 1)
    
    list_forum = Forum.objects.all()
    list_comment = Comment.objects.all()
    paginate_forum = paginate(page ,list_forum)
    response['form_list'] = paginate_forum['data']
    response['comment_list'] = list_comment
    response['page_range'] = paginate_forum['page_range']
    html = 'tugas2/tugas2.html'
    return render(request, html, response)

def paginate(request, forum_list):
    # Bagian paginator
    paginator = Paginator(forum_list, 1)

    try:
        forum_new = paginator.page(request)
    except PageNotAnInteger:
        forum_new = paginator.page(1)
    except EmptyPage:
        forum_new = paginator.page(paginator.num_pages)

    index = forum_new.number - 1

    max_index = len(paginator.page_range)

    start_index = index if index >= 10 else 0
    end_index = 1 if index < max_index - 10 else max_index

    page_range = list(paginator.page_range)[start_index:end_index]

    data_paginate = {'data': forum_new, 'page_range': page_range}
    return data_paginate

def add_comment(request):
    form = Lowongan_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['nama'] = request.POST['nama']
        response['description'] = request.POST['description']
        comment = Comment(nama=response['nama'],description=response['description'], forum=Forum.objects.get(id=1))
        comment.save()
        return HttpResponseRedirect('/appnyajadi-1/')
    else:
        return HttpResponseRedirect('/appnyajadi-1/')
#############   index lila
#def index(request):
    # print ("#==> masuk index")
  #  if 'user_login' in request.session:
   #     return HttpResponseRedirect(reverse('forumku:dashboard'))
   # else:
    #    response['author'] = get_data_user(request, 'user_login')
     #   html = 'fitur_forum/login.html'
      #  return render(request, html, response)


def dashboard(request):

   # if not 'login' in request.session:
        # nanti ganti linknya dengan halaman login
    #    print("GAGAL")
   #     return HttpResponseRedirect(reverse('appnyajadi-1:index'))
    
   # if not 'user_login' in request.session.keys():
     #   return HttpResponseRedirect(reverse('appnyajadi-1:index'))
  #  else:

        #nama = request.session['login']
        #kode_identitas = get_data_user(request, 'kode_identitas')
        #try:
        company = Company.objects.get(kode_identitas = kode_identitas)
        #except Exception as e:
        #    pengguna = create_new_user(request)

        forum = Forum.objects.filter(company=company)
        
        response['message'] = message
        response['message_form'] = Message_Form
        response["message_list"] = message
       
        html = 'tugas2/fitur_forum.html'
        
        message_list = message
        paginator = Paginator(message_list, 5)
        page = request.GET.get('page', 1)
        try:
            users = paginator.page(page)
        except PageNotAnInteger:
            users = paginator.page(1)
        except EmptyPage:
            users = paginator.page(paginator.num_pages)
       
        response["message_list"] = users
        #response["nama"] = nama
        response["forum"] = forum
        html = 'tugas2/fitur_forum.html'
        return render(request, html, response)

def add_forum(request, id):
    response['id'] = id
    form = Message_Form(request.POST or None)

    if (request.method == 'POST' and form.is_valid()):
        nama = request.POST['nama']
        isi = request.POST['isi']
        nomor = request.POST['nomor']

       # kode_identitas = get_data_user(request, 'kode_identitas')
        #try:
        pengguna = Pengguna.objects.get(company_name = nama)
        # except Exception as e:
        #    pengguna = create_new_user(request)  
     
        response['title'] = request.POST['title'] 
        response['message'] = request.POST['message']
        message = Message(pengguna=pengguna,title=response['title'], message=response['message'], kode_message = id)
        message.save()
        response['id'] = id

        forum = Forum()
        forum.pengguna = pengguna
        forum.isi = isi
        forum.nomor = nomor
        forum.save()

        html ='tugas2/fitur_forum.html'    
        return HttpResponseRedirect('/appnyajadi-1/')


def paginate_page(page, data_list):
    paginator = Paginator(data_list, 5)

    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    # Get the index of the current page
    index = data.number - 1
    # This value is maximum index of your pages, so the last page - 1
    max_index = len(paginator.page_range)
    # You want a range of 10, so lets calculate where to slice the list
    start_index = index if index >= 5 else 0
    end_index = 5 if index < max_index - 5 else max_index
    # Get our new page range. In the latest versions of Django page_range returns 
    # an iterator. Thus pass it to list, to make our slice possible again.
    page_range = list(paginator.page_range)[start_index:end_index]
    paginate_data = {'data':data, 'page_range':page_range}



def delete_forum(request, id_status):
    forum = Message.objects.get(pk = id_status)
    forum.delete()
    return HttpResponseRedirect('/appnyajadi-1/')

appnyajadi_1/templates/tugas2/dashboard.html
{% extends "lab_10/layout/base.html" %}

{% block header %}
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">IQBAL</a>
    </div>
    
    


  </div><!-- /.container-fluid -->
</nav>  
{% endblock %}

{% block content %}
<!-- Content Here -->
<section id="data-dashboard">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2> Dashboard </h2>
        </div>
        <div class="panel-body">
            <p> Username : {{ author }} </p>
            <p> NPM : {{kode_identitas}} </p>
            <p> Role : {{ role }} </p>
            <p>
                <a href="{% url 'lab-10:movie_list' %}" class="btn btn-primary"> Daftar Movie </a>
                <a href="{% url 'lab-10:list_watch_later' %}" class="btn btn-warning"> Daftar Watch Later </a>
            </p>
        </div>
    </div>
</section>
<hr>

{% endblock %}

appnyajadi_1/templates/tugas2/fitur_forum.html
{% extends "fitur_forum/layout/base.html" %}
{% load staticfiles %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/forum.css' %}" />
<h2 class="main-title" style="font-weight:bold; font-size: 50px"> JOB FORUM </h2>

{% block header %}
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
            </button>
            <a target="_blank" href="#" class="navbar-brand"> Forum Lowongan Pekerjaan</a>
        </div>
        <div class="collapse navbar-collapse">
            
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-user"></span> 
                        <strong> Lila Asfari</strong>
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <div class="navbar-login">
                                <div class="row">
                                    <div class="col-lg-4">
                                        <p class="text-center">
                                            <span class="glyphicon glyphicon-user icon-size"></span>
                                        </p>
                                    </div>
                                    <div class="col-lg-8">
                                        <p class="text-left"><strong>Lila Asfari</strong></p>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="navbar-login navbar-login-session">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <p>
                                            <a href="{% url 'forumku:auth_logout' %}" class="btn btn-danger btn-block" onclick="return confirm('Keluar?')">Logout</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}

{% block content %}

<div class="jumbotron jumbotron-fluid text-center" style="margin-bottom: 0px; margin-top: 0px; background-image: url(https://imgur.com/a/fCOEx.jpg)">    
  <div class="container">
    <img class="rounded-circle" src="{% static 'image/logo.png' %}" alt="Generic placeholder image" style="width:270px;height:175px;">
    <h1 class="display-3" style="font-family: sans-serif ;">Forum Lowongan Pekerjaan</h1>
    <h4 class="lead" style="fontfamily: Lucida">Temukan lowongan pekerjaan disini!</h4>
  </div>
</div>

<section name="my-list" id="show-forum" style="padding-bottom: 20px; padding-top: 0px">
    {% if message_list %}
        {% for data in message_list %}
            <div class="container" style="padding-top: 0px">
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                        <div class="media" style="padding: 40px">
                            <div class="media-left">
                                <a href="https://ibb.co/gwytub">
                                  <img src="https://thumb.ibb.co/gwytub/architecture_1448221_960_720.jpg" alt="architecture_1448221_960_720" border="0" class="media-object img-circle" style="width:75px">
                                </a>
                            </div>
                            <div class="media-body">
                                <a href="/forumku/delete_forum/{{ data.id }}" class="close">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                                <h4 class="media-heading"><strong>{{data.title}}</strong> <small><i>Posted on {{data.created_date}}</i></small></h4>
                                <p>{{data.message}}</p>
                                

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
         <div class="container text-center"  style="padding-top: 15px;">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    <div id="empty" class="alert alert-danger">
                        <strong>Oops!</strong> Belum ada forum.
                    </div>
                    
                </div>
            </div>
            
        </div>
    {% endif %}
    
</section>


{% if message_list.has_other_pages %}
    <ul class="pagination">
        {% if message_list.has_previous %}
            <li><a href="?page={{ message_list.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        {% for i in message_list.paginator.page_range %}
            {% if message_list.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if message_list.has_next %}
              <li><a href="?page={{ message_list.next_page_number }}">&raquo;</a></li>
        {% else %}
              <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
{% endif %}

<section name="form" id = post-forum>
    <h2>Job Forum</h2>
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <form id="form" method="POST" action="{% url 'forumku:add_message' id %}">
                  {% csrf_token %}
                  {{ message_form }}
                  <button type="submit" class="btn btn-default">Submit</button>
                  <br>
                </form>
            </div>
        </div>
        
    </div>
</section>



{% endblock %}

appnyajadi_1/templates/tugas2/login.html
{% extends "fitur_forum/layout/base.html" %}

{% block content %}
<div class="navbar navbar-default navbar-fixed-top" role="navigation" >
    <div class="container"> 
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
            </button>
            <a href="#" class="navbar-brand">Lab 9</a>
        </div>
    </div>
</div>
<div class="row" style="margin-top: 50px">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'forumku:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

appnyajadi_1/templates/tugas2/tugas2.html
{% extends "tugas2/layout/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container">
	<h3 id="lowongan">Lowongan Kerja</h3>
	<section id="forum" class="row">
		<div class="list-group">
            {% if form_list %}
                {% for form in form_list %}
                    <a class="list-group-item clearfix">
                        <p>{{ form.pengguna.company_name }} </p>
                        <p>{{ form.isi}}</p>
                    </a>
                    <h2>bagian comment</h2>
                    {% for comment in comment_list %}

                      {% if comment.forum == form %}
                      <a class="list-group-item clearfix">
                          <p>{{ comment.nama }}</p>
                          <p>{{ comment.description}}</p>
                      </a>
                      {% endif %}
                    {% endfor %}
                {% endfor %}

            {% else %}
                <div class="alert alert-danger text-center">
                    <strong>Oops!</strong> Tidak ada Forum
                </div>
            {% endif %}
            
        </div>
	</section>

	<section id="comment" class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-10">
            <section name="input-list" id="input-list">
                <div class="col-sm-12">

                    <div id="avatar_perusahaan" class="col-sm-4">
                        IMG
                    </div>
                    <div id="form_perusahaan" class="col-sm-8">
                        <form id="form" method="POST" action="{% url 'appnyajadi-1:add_comment' %}">
                            {% csrf_token %}

                            {{ lowongan_form}}
                            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                            <br>
                        </form> 
                    </div>
                </div>

            </section>     
        </div>
	</section>

	<section id="pagination">
		{% if form_list.has_other_pages %}
                <ul class="pagination">
                    {% if form_list.has_previous %}
                        <li><a href="{% url 'appnyajadi-1:index' %}">&laquo;</a></li>
                        <li><a href="?page={{ form_list.previous_page_number }}">&lsaquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&lsaquo;</span></li>
                    {% endif %}
                    {% for page in page_range %}
                        {% if mahasiswa_list.number == page %}
                            <li class="active"><span>{{ page }} <span
                                    class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page={{ page }}">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if form_list.has_next %}
                        <li><a href="?page={{ form_list.next_page_number }}">&rsaquo;</a></li>
                        <li><a href="?page={{ form_list.paginator.num_pages }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><span>&rsaquo;</span></li>
                    {% endif %}
                </ul>
            {% endif %}
	</section>
		


	<section id="login" class="row">
		<script type="in/Login"></script>

	</section>
</div>

    <!-- display profile info -->
    <!-- display profile info -->
<div id="profileData" style="display: none;">
    <p><a href="javascript:void(0);" onclick="logout()">Logout</a></p>
    
    <div class="info">
        <p id="name"> </p>
        <p id="intro"> </p>
        <p id="email"> </p>
        <p id="location"> </p>
        <p id="link"> </p>
        <form id="form" method="POST" action="{% url 'appnyajadi-1:dashboard'%}">
             {% csrf_token %}
                  {{ message_form }}
                  <button type="submit" class="btn btn-default">Forum Lowongan Pekerjaan</button>
                  <br>
                </form>
    </div>
</div>
<!-- bootstrap csss -->

     

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="{{author}}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/tugas2_Profile.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
    <!-- bootstrap csss -->


</head>
<div class="container" id="bgContent">
      <div id = "over" class="text-center">
        <h3 style="text-align:center; color: black">
        <small><em> <p style="color: black"> <b> Welcome! </b> </p> </em></small>
        <hr style="border: 0.5px solid black" />​
        </h3>

        <img class="image-fluid"  src = "http://www.otextechnology.com/images/services/hucapital.png" style= "max-width:18%; max-height: 500px;  border-radius: 50%; margin-top: 20px">

        <h2 id = "namaPerusahaan" style="color:black text-align: center;"><b>Nama Perusahaan</b></h2>
        <h4 id = "deskripsi" style="color:black text-align: center;"> Deskripsi Perusahaan</h4>
        
        <a href="{% url 'appnyajadi-1:dashboard'%}"><button class = "button"> lihat forum</button></a>
        <button class = "button"> Cari Mahasiswa</button>

    </div>

  <content >
  <hr style="border: 1px solid black" />​
      <div class="row">
          <table style="width:50%; margin-top: 5px; margin-left: 400px ;" align= "center";>
          <style>
            table, th, td {
              color: black;
              height: 35px;
              align-content: center;
            }
          </style>
              <tr >
              <th>Nama Perusahaan</th>
              <td id = "name"><b></b></td>
              </tr>

              <tr>
              <th >Introduction</th>
              <td id = "intro"><b></b></td>
              </tr>

              <tr>
              <th >email Perusahaan</th>
              <td id = "email"><b></b></td>
              </tr>


              <tr>
              <th >Lokasi</th>
              <td id = "lokasi"><b></b></td>
              </tr>

          </table>
          <p></p>
          <hr style="border: 1px solid black" />​
         
      </div>
       <hr style="border: 1px solid black">​
  </div>

  </content>
</div>


<script type="text/javascript">
  console.log("coba atas")
  getSessionDataCompany();

  function getSessionDataCompany(){
    console.log("ahha");
    var company = JSON.parse(sessionStorage.company);
    console.log (company);
    console.log("ahha");
    document.getElementById("namaPerusahaan").innerHTML = company.name;
    document.getElementById("deskripsi").innerHTML = '"'+company.description + '"';
    document.getElementById("tipe").innerHTML = company.companyType.name;
    document.getElementById("Year").innerHTML = company.foundedYear;
    document.getElementById("website").innerHTML = company.websiteUrl;
    document.getElementById("Spesialisasi").innerHTML = company.specialties.values[0] + ", " + company.specialties.values[1];

  }

</script>
</html>
{% endblock %}